/**
 * TypeScript types derived from schemas/helpline.schema.json
 *
 * SOURCE OF TRUTH: schemas/helpline.schema.json
 * Do not edit this file manually — regenerate with `npm run build:types` in packages/core.
 *
 * Generated from JSON Schema via json-schema-to-typescript.
 */

export type LanguageCode = string; // BCP-47, e.g. "en", "ja", "fr-CA"
export type CountryCode = string;  // ISO 3166-1 alpha-2, e.g. "JP", "US"
export type E164PhoneNumber = string; // E.164 format, e.g. "+18002738255"
export type IsoDate = string;      // YYYY-MM-DD
export type HttpUrl = string;      // https://...

export type ServiceCategory =
  | "suicide_prevention"
  | "mental_health"
  | "domestic_violence"
  | "sexual_violence"
  | "substance_abuse"
  | "youth"
  | "lgbtq"
  | "veterans"
  | "elder"
  | "grief"
  | "general_crisis"
  | "other";

export type ContactMethod = "phone" | "text" | "chat" | "email" | "app";

export interface HelplineContact {
  /** Primary contact method */
  method: ContactMethod;
  /** E.164 phone number (required when method is "phone" or "text") */
  number?: E164PhoneNumber;
  /** URL for chat, app, or email contact */
  url?: HttpUrl;
  /** BCP-47 language codes this contact supports */
  languages: LanguageCode[];
  /** Operating hours in local time. "24/7" or human-readable string */
  hours: string;
  /** Whether this contact is free of charge */
  free: boolean;
  /** Indicates contact is available to all regardless of citizenship */
  anonymous?: boolean;
}

export interface HelplineRecord {
  /** Unique slug: "{country_code}-{slug}", e.g. "jp-inochi-no-denwa" */
  id: string;
  /** ISO 3166-1 alpha-2 country code */
  country: CountryCode;
  /** Human-readable organization name in English */
  name: string;
  /** Name in local language (omit if same as name) */
  local_name?: string;
  /** Primary service category */
  category: ServiceCategory;
  /** Additional categories if the service covers multiple populations */
  secondary_categories?: ServiceCategory[];
  /** Available contact methods */
  contacts: HelplineContact[];
  /** Short description (max 280 chars) in English */
  description: string;
  /** Organization website */
  website?: HttpUrl;
  /** ISO 8601 date the record was last verified */
  verified_at: IsoDate;
  /** Source URL or citation for the data */
  source: HttpUrl;
  /** Whether this is an official government-backed service */
  government_backed: boolean;
  /** Tags for additional filtering (lowercase, hyphenated) */
  tags?: string[];
}

export interface CountryIndex {
  /** ISO 3166-1 alpha-2 */
  country: CountryCode;
  /** English country name */
  name: string;
  /** Paths to JSON data files relative to repo root */
  data_files: string[];
  /** Total number of helpline records */
  record_count: number;
  /** ISO 8601 timestamp of last update */
  updated_at: string;
}

export interface GlobalIndex {
  /** Schema version for this index file */
  schema_version: string;
  /** ISO 8601 timestamp of last rebuild */
  generated_at: string;
  /** All countries in the registry */
  countries: CountryIndex[];
  /** Total helpline records across all countries */
  total_records: number;
}
