/**
 * Fallback data for when the real helplines.json cannot be fetched.
 *
 * Used as a safety net in useHelplinesData() when the network request fails
 * (e.g. local dev without running collect-data, or a build artefact issue).
 *
 * Note: records arrays are intentionally empty here — the fallback only
 * provides country-level stats so the globe and charts can still render.
 */

import type { GlobalHelplinesData } from '@/types/helpline';

export const FALLBACK_GLOBAL_DATA: GlobalHelplinesData = {
  generatedAt: '2026-06-02T00:00:00Z',
  totalRecords: 21,
  countries: [
    {
      countryCode: 'JP',
      countryName: 'Japan',
      lat: 36.2048,
      lng: 138.2529,
      helplineCount: 3,
      categories: ['suicide_prevention', 'mental_health', 'general_crisis'],
      contactMethods: ['phone'],
      languages: ['ja', 'en', 'zh', 'ko', 'es', 'pt', 'fil', 'th', 'vi', 'ne', 'id'],
      records: [],
    },
    {
      countryCode: 'US',
      countryName: 'United States',
      lat: 37.0902,
      lng: -95.7129,
      helplineCount: 2,
      categories: ['suicide_prevention', 'mental_health', 'lgbtq', 'veteran'],
      contactMethods: ['phone', 'text', 'chat'],
      languages: ['en', 'es'],
      records: [],
    },
    {
      countryCode: 'GB',
      countryName: 'United Kingdom',
      lat: 55.3781,
      lng: -3.4360,
      helplineCount: 2,
      categories: ['suicide_prevention', 'mental_health'],
      contactMethods: ['phone', 'text', 'chat', 'email'],
      languages: ['en'],
      records: [],
    },
    {
      countryCode: 'IN',
      countryName: 'India',
      lat: 20.5937,
      lng: 78.9629,
      helplineCount: 2,
      categories: ['suicide_prevention', 'mental_health'],
      contactMethods: ['phone'],
      languages: ['en', 'hi'],
      records: [],
    },
    {
      countryCode: 'RU',
      countryName: 'Russia',
      lat: 61.5240,
      lng: 105.3188,
      helplineCount: 2,
      categories: ['suicide_prevention', 'mental_health', 'crisis'],
      contactMethods: ['phone'],
      languages: ['ru'],
      records: [],
    },
    {
      countryCode: 'AU',
      countryName: 'Australia',
      lat: -25.2744,
      lng: 133.7751,
      helplineCount: 1,
      categories: ['suicide_prevention', 'mental_health', 'crisis'],
      contactMethods: ['phone', 'chat'],
      languages: ['en'],
      records: [],
    },
    {
      countryCode: 'BD',
      countryName: 'Bangladesh',
      lat: 23.6850,
      lng: 90.3563,
      helplineCount: 1,
      categories: ['suicide_prevention', 'mental_health'],
      contactMethods: ['phone'],
      languages: ['bn'],
      records: [],
    },
    {
      countryCode: 'BR',
      countryName: 'Brazil',
      lat: -14.2350,
      lng: -51.9253,
      helplineCount: 1,
      categories: ['suicide_prevention', 'crisis'],
      contactMethods: ['phone'],
      languages: ['pt'],
      records: [],
    },
    {
      countryCode: 'CA',
      countryName: 'Canada',
      lat: 56.1304,
      lng: -106.3468,
      helplineCount: 1,
      categories: ['suicide_prevention', 'crisis', 'mental_health'],
      contactMethods: ['phone', 'text', 'chat'],
      languages: ['en', 'fr'],
      records: [],
    },
    {
      countryCode: 'CN',
      countryName: 'China',
      lat: 35.8617,
      lng: 104.1954,
      helplineCount: 1,
      categories: ['suicide_prevention', 'mental_health'],
      contactMethods: ['phone'],
      languages: ['zh'],
      records: [],
    },
    {
      countryCode: 'DE',
      countryName: 'Germany',
      lat: 51.1657,
      lng: 10.4515,
      helplineCount: 1,
      categories: ['suicide_prevention', 'general_crisis'],
      contactMethods: ['phone'],
      languages: ['de'],
      records: [],
    },
    {
      countryCode: 'FR',
      countryName: 'France',
      lat: 46.2276,
      lng: 2.2137,
      helplineCount: 1,
      categories: ['suicide_prevention'],
      contactMethods: ['phone'],
      languages: ['fr'],
      records: [],
    },
    {
      countryCode: 'ID',
      countryName: 'Indonesia',
      lat: -0.7893,
      lng: 113.9213,
      helplineCount: 1,
      categories: ['suicide_prevention', 'mental_health'],
      contactMethods: ['phone'],
      languages: ['id'],
      records: [],
    },
    {
      countryCode: 'KR',
      countryName: 'South Korea',
      lat: 35.9078,
      lng: 127.7669,
      helplineCount: 1,
      categories: ['suicide_prevention', 'mental_health'],
      contactMethods: ['phone'],
      languages: ['ko'],
      records: [],
    },
    {
      countryCode: 'MX',
      countryName: 'Mexico',
      lat: 23.6345,
      lng: -102.5528,
      helplineCount: 1,
      categories: ['suicide_prevention', 'mental_health', 'crisis'],
      contactMethods: ['phone'],
      languages: ['es'],
      records: [],
    },
    {
      countryCode: 'PH',
      countryName: 'Philippines',
      lat: 12.8797,
      lng: 121.7740,
      helplineCount: 1,
      categories: ['suicide_prevention', 'mental_health'],
      contactMethods: ['phone'],
      languages: ['tl', 'en'],
      records: [],
    },
  ],
};
