/**
 * Mock data for development and testing.
 * Used when real data from open-helplines/data/countries/ is not yet available.
 * This file is replaced by the build-time data pipeline once Task #1 merges.
 */

import type { GlobalHelplinesData } from '@/types/helpline';

export const MOCK_GLOBAL_DATA: GlobalHelplinesData = {
  generatedAt: '2026-06-02T00:00:00Z',
  totalRecords: 24,
  countries: [
    {
      countryCode: 'JP',
      countryName: 'Japan',
      lat: 36.2048,
      lng: 138.2529,
      helplineCount: 5,
      categories: ['suicide_prevention', 'mental_health', 'general_crisis'],
      contactMethods: ['phone', 'chat'],
      languages: ['ja', 'en', 'zh', 'ko'],
      records: [],
    },
    {
      countryCode: 'AU',
      countryName: 'Australia',
      lat: -25.2744,
      lng: 133.7751,
      helplineCount: 4,
      categories: ['suicide_prevention', 'crisis', 'lgbtq'],
      contactMethods: ['phone', 'chat', 'text'],
      languages: ['en'],
      records: [],
    },
    {
      countryCode: 'US',
      countryName: 'United States',
      lat: 37.0902,
      lng: -95.7129,
      helplineCount: 6,
      categories: ['suicide_prevention', 'crisis', 'lgbtq', 'veteran', 'domestic_violence'],
      contactMethods: ['phone', 'text', 'chat'],
      languages: ['en', 'es'],
      records: [],
    },
    {
      countryCode: 'GB',
      countryName: 'United Kingdom',
      lat: 55.3781,
      lng: -3.4360,
      helplineCount: 4,
      categories: ['suicide_prevention', 'mental_health', 'crisis'],
      contactMethods: ['phone', 'email', 'chat'],
      languages: ['en'],
      records: [],
    },
    {
      countryCode: 'CA',
      countryName: 'Canada',
      lat: 56.1304,
      lng: -106.3468,
      helplineCount: 3,
      categories: ['suicide_prevention', 'crisis'],
      contactMethods: ['phone', 'chat'],
      languages: ['en', 'fr'],
      records: [],
    },
    {
      countryCode: 'DE',
      countryName: 'Germany',
      lat: 51.1657,
      lng: 10.4515,
      helplineCount: 2,
      categories: ['suicide_prevention', 'general_crisis'],
      contactMethods: ['phone'],
      languages: ['de'],
      records: [],
    },
    {
      countryCode: 'FR',
      countryName: 'France',
      lat: 46.2276,
      lng: 2.2137,
      helplineCount: 2,
      categories: ['suicide_prevention', 'mental_health'],
      contactMethods: ['phone'],
      languages: ['fr'],
      records: [],
    },
    {
      countryCode: 'IN',
      countryName: 'India',
      lat: 20.5937,
      lng: 78.9629,
      helplineCount: 3,
      categories: ['suicide_prevention', 'mental_health', 'domestic_violence'],
      contactMethods: ['phone', 'chat'],
      languages: ['en', 'hi'],
      records: [],
    },
    {
      countryCode: 'BR',
      countryName: 'Brazil',
      lat: -14.2350,
      lng: -51.9253,
      helplineCount: 2,
      categories: ['suicide_prevention', 'crisis'],
      contactMethods: ['phone'],
      languages: ['pt'],
      records: [],
    },
    {
      countryCode: 'KR',
      countryName: 'South Korea',
      lat: 35.9078,
      lng: 127.7669,
      helplineCount: 2,
      categories: ['suicide_prevention', 'mental_health'],
      contactMethods: ['phone', 'chat'],
      languages: ['ko'],
      records: [],
    },
    {
      countryCode: 'NZ',
      countryName: 'New Zealand',
      lat: -40.9006,
      lng: 174.8860,
      helplineCount: 2,
      categories: ['suicide_prevention', 'crisis'],
      contactMethods: ['phone', 'text'],
      languages: ['en'],
      records: [],
    },
    {
      countryCode: 'ZA',
      countryName: 'South Africa',
      lat: -30.5595,
      lng: 22.9375,
      helplineCount: 1,
      categories: ['suicide_prevention'],
      contactMethods: ['phone'],
      languages: ['en'],
      records: [],
    },
    {
      countryCode: 'NG',
      countryName: 'Nigeria',
      lat: 9.0820,
      lng: 8.6753,
      helplineCount: 1,
      categories: ['mental_health'],
      contactMethods: ['phone'],
      languages: ['en'],
      records: [],
    },
    {
      countryCode: 'PK',
      countryName: 'Pakistan',
      lat: 30.3753,
      lng: 69.3451,
      helplineCount: 1,
      categories: ['general_crisis'],
      contactMethods: ['phone'],
      languages: ['ur', 'en'],
      records: [],
    },
  ],
};
